c1=str(input("dati un cuvant"))
c2=str(input("dati un cuvant"))
c3=str(input("dati un cuvant"))
c4=str(input("dati un cuvant"))
print("cuvantul 1 este",c1)
print("cuvantul 2 este",c2)
print("cuvantul 3 este",c3)
print("cuvantul 4 este",c4)
print(c1 + " " + c2 + " "+c3  + " " + c4 + ".")
